#!/bin/bash

#library version
#rustup component add rust-src --toolchain nightly-2024-08-20

export __CARGO_TESTS_ONLY_SRC_ROOT=$(pwd)/library

cargo new dummy
cd dummy
echo '[toolchain]
channel = "nightly-2024-08-20"
components = ["rust-src", "rustc-dev", "llvm-tools", "rustfmt"]' > ./rust-toolchain

case "$(uname -s)" in
    Darwin) target="x86_64-apple-darwin" ;;
    Linux) target="x86_64-unknown-linux-gnu" ;;
    *) echo "Unsupported OS"; exit 1 ;;
esac

FLUX_CATCH_BUGS=1 cargo flux -Z build-std --target "$target" > ../log.txt

cd ..
rm -rf dummy